### ISSUE TITLE
dessert house

### ISSUE THREAD

**Issue by bokov-andrew** [Leoists/leoneor_mc#2]
What are you requesting?

- [x]  New creative region
- [ ]  New survival region
- [ ] New protected region
- [ ] New other region (what?)

Please give us your xyz of opposite corners of the region (to find out coordinates, hit F3 while playing)
     
at end of ice bridge

What do you plan to do there?

build a house

Do you agree to read the rules __and follow them__, including the part about __never transferring items from creative mode to survival mode__?

yes

**Comment by bokov** [comment]
Done. Follow Icebridge to the end, look for enormous cactus.
